dist: xenial
language: python
sudo: required
python:
  - "3.7.3"
cache: pip
install:
  - pip install -U pip
  - pip install -U --no-cache-dir --force-reinstall Red-DiscordBot[style]
script:
  - python -m compileall .
  - black --check -l 99 `git ls-files "*.py"`
notifications:
  email: false
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL