dist: xenial
language: python
sudo: required
python:
  - "3.7.2"
cache: pip
install:
  - pip install -U pip==18.1
  - pip install -U --process-dependency-links --no-cache-dir --force-reinstall Red-DiscordBot
  - pip install -U black==18.9b0
script:
  - python -m compileall .
  - black --check -l 99 -N `git ls-files "*.py"`
notifications:
  email: false
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL